<div id="wrapper">

	<div id="content-wrapper">
		
		<!-- If model is not selected does not show left data selection bar
			 nor render the contents -->
		<?php if ( true == $this->isModelSelected ): ?>
        
            <div id="content">
                <?php if(isset($this->chart)): ?>
                    <?php echo $this->chart; ?>
                <?php else: ?>
                    <? if(!isset($this->parser)): ?>
                    <i><?php echo $this->_('info chart display selection first'); ?></i>
                    <? else: ?>
                    <i><?php echo $this->_('info chart type change'); ?></i>
                    <? endif; ?>
                <?php endif;?>
            </div>
        
        <?php else: ?> 
        
            <div id="content">
                <script type="text/javascript">
                    $(function() {
                        Namespace.include('org.aksw.cubeViz.Index.Main');
                        $("#sidebar-left-arrow").hide ();
                        org.aksw.cubeViz.Index.Main.loadPage ('startNoModelGiven');
                    });
                </script>
            </div>
        
        <?php endif; ?>
        
        <div id="site-overlay">&nbsp;</div>
        
	</div>
</div>

<!-- If model is not selected does not charts icon set-->
<?php if ( true == $this->isModelSelected ): ?>
<div id="chart-selection">
    <div id="chart-selection-container">
        <!-- If you add new chart option, please, redefine org.aksw.cubeViz.Index.Main.availableChartTypes
             in index.js file-->
        <img id="chart-selection-bar" src="<?php echo $this->basePath; ?>images/bars.png"/>
        <img id="chart-selection-line" src="<?php echo $this->basePath; ?>images/lines.png"/>
        <img id="chart-selection-area" src="<?php echo $this->basePath; ?>images/areas.png"/>
        <img id="chart-selection-splines" src="<?php echo $this->basePath; ?>images/splines.png"/>
        <img id="chart-selection-table" src="<?php echo $this->basePath; ?>images/table.png"/>
        <input type="hidden" id="chart-selection-selected-chart" value="bars">
    </div>
</div>
<?php endif; ?>
