default:

prepare:
	rm -f ../../Makefile
	rm -f ../../classes/foreign/EasyRdf/LICENSE.md
	rm -f ../../public/images/semicon/LICENSE.md
	cp ../../doap.n3.dist ../../doap.n3
	cp ../../ChartConfig.js.dist ../../ChartConfig.js

clean:
	rm -rf ../files
	rm -rf ../*.debhelper.log
	rm -rf ../*.substvars
	rm -rf ../ontowiki-cubeviz

