<!-- Libraries -->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts.js"></script>
<!--<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts.src.js"></script>-->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts-more.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/json2.js"></script>

<!-- generated Javascript -->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/frontend/Cubeviz_Viz.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>/ChartConfig.js"></script>

<style type="text/css">
    @import url("<?php echo $this->basePath; ?>static/css/main.css");
</style>

<?php require_once ('extensions/cubeviz/static/templates/ChartSelectorTemplate.phtml'); ?>

<script>
    /**
     * Contains loaded configuration for given hashcode
     * default is "default" configuration
     */
    var CubeViz_Links_Module = CubeViz_Links_Module || <?php echo $this->linkConfiguration; ?>;
	
    // Name of choosen config; default is "default"
    CubeViz_Links_Module ["linkCode"] = CubeViz_Links_Module ["linkCode"] || <?php echo json_encode($this->linkCode); ?>; 
    CubeViz_Links_Module ["backend"] = CubeViz_Links_Module ["backend"] || <?php echo json_encode($this->backend); ?>;
    CubeViz_Links_Module ["cubevizPath"] = CubeViz_Links_Module ["cubevizPath"] || <?php echo json_encode($this->cubevizPath); ?>;		
    CubeViz_Links_Module ["modelUrl"] = CubeViz_Links_Module ["modelUrl"] || "<?php echo $this->modelUrl; ?>";		
	CubeViz_Links_Module ["sparqlEndpoint"] = CubeViz_Links_Module ["sparqlEndpoint"] || "local"; 
	
    /**
     * Contains system information related only to CubeViz
     */
    var CubeViz_Config = {
        "context": "development",   // possible: development, production
        "imagesPath": <?php echo json_encode($this->cubevizImagesPath); ?>
    };
    
    var cubeVizUIChartConfig = <?php echo $this->cubeVizUIChartConfig; ?>; 
</script>

<div id="wrapper-index" scrolling="no">
    <div id="container"></div>
    <div id="chartSelection" scrolling="no"></div>
</div>

<div id="chartSelectionMenu" lastSelection="0"></div>
