<!-- Libraries -->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/json2.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/namespacedotjs/Namespace.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/json-template.min.js"></script>

<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/frontend/CubeVizController.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>data/ChartConfig.js"></script>
<!-- script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/frontend/CubeVizChartSelection.js"></script-->

<style type="text/css">
    @import url("<?php echo $this->basePath; ?>static/css/main.css");
</style>

<script>
    /*************************************
     * Importing Server-Side System Info *
     *************************************/
    Namespacedotjs.baseUri = <?php echo json_encode($this->basePath . 'static/javascript/frontend/'); ?>;

    var CubeViz_Link_Chosen_Component = <?php echo json_encode($this->linkCode); ?>;
    
    var CubeViz_Parameters_Component = {
		sparqlEndpoint: <?php echo $this->sparqlEndpoint; ?>,
		selectedGraph: null,
		selectedDSD: {},
		selectedDS: {},
		selectedMeasures: {},
		selectedDimensions: {},
		selectedDimensionComponents: {}
	}
		
	CubeViz_Parameters_Component.modelUrl = "<?php echo $this->modelUrl; ?>";		
	CubeViz_Parameters_Component.cubevizPath = <?php echo json_encode($this->cubevizPath); ?>;		
	CubeViz_Parameters_Component.cubevizImagesPath = "<?php echo $this->basePath_images; ?>";		
	CubeViz_Parameters_Component.backend = <?php echo json_encode($this->backend); ?>;		
	CubeViz_Parameters_Component.visualizationContainer = "container";		
    CubeViz_Parameters_Component.preferredChartType = "bar";   
</script>

<div id="wrapper-index">
    
    <div id="container" style="top:65px"></div>
    <div id="chartSelection"></div>
</div>
