<!-- Libraries -->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/CryptoJs/md5-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/highcharts-more.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/libraries/json2.js"></script>

<!-- generated Javascript -->
<script type="text/javascript" src="<?php echo $this->basePath; ?>static/javascript/frontend/Cubeviz_Viz.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath; ?>/ChartConfig.js"></script>

<style type="text/css">
    @import url("<?php echo $this->basePath; ?>static/css/main.css");
    @import url("<?php echo $this->basePath; ?>static/css/IndexAction.css");
</style>

<?php require_once ('extensions/cubeviz/static/templates/ChartSelectorTemplates.phtml'); ?>
<?php require_once ('extensions/cubeviz/static/templates/Visualization_CubeViz_Templates.phtml'); ?>

<script>
    /**
     * Contains loaded configuration for given hashcode
     * default is "default" configuration
     */
    var CubeViz_Links_Module = CubeViz_Links_Module || <?php echo $this->linkConfiguration; ?>;
	
    CubeViz_Links_Module ["linkCode"] = CubeViz_Links_Module ["linkCode"] || <?php echo json_encode($this->linkCode); ?>; 
    CubeViz_Links_Module ["backend"] = CubeViz_Links_Module ["backend"] || <?php echo json_encode($this->backend); ?>;
    CubeViz_Links_Module ["cubevizPath"] = CubeViz_Links_Module ["cubevizPath"] || <?php echo json_encode($this->cubevizPath); ?>;		
    CubeViz_Links_Module ["modelUrl"] = CubeViz_Links_Module ["modelUrl"] || "<?php echo $this->modelUrl; ?>";		
	CubeViz_Links_Module ["sparqlEndpoint"] = CubeViz_Links_Module ["sparqlEndpoint"] || "local"; 
	
    /**
     * Contains system information related only to CubeViz
     */
    var CubeViz_Config = {
        "context": "development",   // possible: development, production
        "imagesPath": <?php echo json_encode($this->cubevizImagesPath); ?>
    };
    
    var cubeVizUIChartConfig = <?php echo $this->cubeVizUIChartConfig; ?>; 
</script>


<!-- 
    Chart rendering area 
-->
<div id="wrapper-index" scrolling="no">
    <h2>
        CubeViz - Visualization of the <?php echo $this->modelTitle; ?>
        &nbsp;
        <img id="cubeviz-Index-questionMarkHeadline" class="cubeviz-icon-small" src="<?php echo $this->cubevizImagesPath; ?>questionmark.png" title="Click for more information"/>
    </h2>
    <div id="container"></div>
    <div id="chartSelection" scrolling="no"></div>
</div>


<!-- 
    Chart Selection menu 
-->
<div id="chartSelectionMenu" lastSelection="0">
    <div id="chartSelectionMenuHeader">
        Configure the visualization
        <img src="<?php echo $this->cubevizImagesPath; ?>grayCross.png" id="chartSelectionMenuCloseCross"/>
    </div>
    <div id="chartSelectionMenuContent"></div>
</div>
<img id="chartSelectionMenuDongle" title="Click to open the menu"/>


<!-- 
    Dialog box for questionmark in headline(cubeviz-Index-questionMarkHeadline) 
-->
<div id="cubeviz-Index-DialogboxHeadline">
    
    <!-- Label -->
    <h2><?php echo $this->modelInformation ['label']; ?></h2>
    
    <!-- Short description -->
    <div style="font-size: 14px;"><?php echo $this->modelInformation ['shortdesc']; ?></div>
        
    <!-- Description -->
    <small><?php echo $this->modelInformation ['description']; ?></small>
    
    <br/>
    <br/>
    <div style="font-size: 14px;">Information:</div>
    
    <ul class="cubeviz-ul-basic">
        <!-- Creator -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>person-pencil.png" class="cubeviz-icon-minimal" title="Creator"/>
            <?php echo $this->modelInformation ['creator']; ?>
        </li>
    
        <!-- Revision -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>version2.png" class="cubeviz-icon-minimal" title="Revision"/>
            Revision: <?php echo $this->modelInformation ['revision']; ?>
        </li>
    
        <!-- Document -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>document.png" class="cubeviz-icon-minimal" title="License"/>
            <?php echo $this->modelInformation ['license']; ?>
        </li>
    </ul>
</div>
