<link rel="stylesheet" type="text/css" href="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/colorbox/colorbox.css"/>
<script type="text/javascript" src="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/colorbox/jquery.colorbox-min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $("a.gallery").colorbox({transition:"none", width:"75%", height:"75%"});
});
</script>

<div style="    margin-top: 0px; 
                margin-left: 0px; 
                min-height: 100%; height:auto !important; height:100%;">
<div>
    <div style="float:right; margin:1em; text-align:center; height:320px">
        <a href="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-home-polar.png" class="gallery" rel="gallery-0" title="CubeViz Output of the Digital Agenda Scoreboard DataCube">
           <img src="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-home-polar.png" style="height:300px">
            <br> CubeViz Polar Chart
        </a>            
    </div>

    <h1 style="font-size: 24px;">CubeViz</h1>
    <span style="font-size: 16px; color: #6386A4;">THE RDF DATACUBE BROWSER</span>
    <p style="margin-top: 1em; color: #4A4A4A; width: 96%;">
        Welcome to CubeViz - the facetted browser for statistical data in the Linked Data Web.
        CubeViz was set up and adopted to be part of the Data Portal of the European Union.
    </p>
    <p style="margin-top: 1em; color: #4A4A4A; width: 96%;">
		Since the amount of available statistical data in the web is increasing in the past years, user-friendly accessibility to such data is becoming equally important            
        There are also numerous statistical datasets published within the DataPortal by the European Commission.
        In dependence of the data format of these datasets (i.e. XLS, CSV), the containing data can be browsed by users with the help of different tools such as Google spreadsheet, Libre Office or MS Office.
        One of the upcoming data formats is the <a href="http://www.w3.org/RDF/" target="_blank">Resource Description Format (RDF)</a> which is designed to represent data not on a 
        document/text level but on a the level of information and facts.
        Furthermore RDF enables publishers to encode not only data items but also underlaying semantics. 
        In order to represent such semantics, domain-specific vocabularies can be re-used or - if not available - can be generated.
        <br> 
        The <a href="http://www.w3.org/TR/vocab-data-cube/" target="_blank">RDF DataCube vocabulary</a> is one of the vocabularies used to encode statistics. 
        There is an increasing amount of tools dealing with RDF in order to facilitate users to browse datasets encoded in this way.
        One of these tools is <a href="http://aksw.org/Projects/OntoWiki.html" target="_blank">OntoWiki</a> that ficilitates users to browse RDF data in a generic way.
        CubeViz was developed based on <em>OntoWiki</em> with the scope of offering user-friendly exploration possibilities for statistical data 
        represented in RDF with the RDF DataCube vocabulary.
    </p>

    <h2 style="margin-top: 1em; font-size: 14px; color: #6386A4;">HowTo, FAQ and Examples</h2>    
    <p style=" color: #4A4A4A; width: 96%;">
        CubeViz represent the statistical dataset to be visualized as a facetted based browsing component (located on the left side of the screen).
        This component enables the users to select interesting parts of the dataset. 
        After selection the user can proceed while clicking on the button <em>Show/Update Chart</em>. 
        One can instantly start using CubeViz while clicking on the button.
        As a result CubeViz processes a chart according to user's selection.
        The current version of CubeViz processes basic chart types - such as <em>line</em>, <em>bar</em> and <em>pie chart</em> facilitating the exploration up to two 
        statistical dimensions in a data structure.
    </p>
    <p style="margin-top: 1em; color: #4A4A4A; width: 96%;">            
        If you need further information of how to use CubeViz have a look on our <a href="<?php echo $_REQUEST ['urlBase']; ?>page/howto">HowTo</a> 
        or <a href="<?php echo $_REQUEST ['urlBase']; ?>page/faq">FAQ</a> page.
        Some impressions of possible outputs are listed on our <a href="<?php echo $_REQUEST ['urlBase']; ?>page/examples">page of examples</a>, where you find explanations on some 
		outputs of the statistical of the <a href="http://scoreboard.lod2.eu/">Digital Agenda Scoreboard of the European Commission</a>. 
    </p>

    <h2 style="margin-top: 1em; font-size: 14px; color: #6386A4;">Screenshots</h2>    
    <p style="color: #4A4A4A; width: 96%;">            
        <div style="float:top">
            <div style="float:left;margin:1em; text-align:center">
                <a href="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-pie.png" class="gallery" rel="gallery-1" title="CubeViz Pie Chart">
                    <img src="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-pie.png" style="height: 200px"><br>            
                    CubeViz Pie Chart
                </a>
            </div>
            <div style="float:left;margin:1em; text-align:center">
                <a href="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-bar.png" class="gallery" rel="gallery-1" title="CubeViz Bar Chart">
                    <img src="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-bar.png" style="height: 200px"><br>            
                    CubeViz Bar Chart
                </a>
            </div>
           <div style="float:left;margin:1em; text-align:center">
                <a href="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-windrose-axisSwitch.png" class="gallery" rel="gallery-1" title="CubeViz Polar Chart with columns and switched axes">
                    <img src="<?php echo $_REQUEST ['urlBase']; ?>extensions/page/page/images/cubeviz-windrose-axisSwitch.png" style="height: 200px"><br>            
                    CubeViz Polar Chart
                </a>
            </div>
        </div>


    </p>
    <div style="clear:both"></div>
    </div>
</div>




        
