<div style="padding: 10px;">
    
    <!-- Header -->
    <div class="hero-unit">
        <h1><?php echo $this->headLabel; ?></h1>
        <?php echo $this->translate->_('AnalyzeAction_HeadDescriptionText'); ?>
    </div>
    
    <div class="row-fluid">
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <?php echo $this->translate->_('AnalyzeAction_DataStructureDefinitions'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->dataStructureDefinitions); ?>
            </div>
        </div>
        
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dataset2.png" 
                         style="width: 17px; margin-left: 10px;"/>
                         
                    &nbsp; &nbsp;
                    <?php echo $this->translate->_('AnalyzeAction_DataSets'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->dataSets); ?>
            </div>
        </div>
        
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                         style="width: 17px; margin-left: 10px;"/>
                         
                    &nbsp; &nbsp; 
                    <?php echo $this->translate->_('AnalyzeAction_Dimensions'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->dimensions); ?>
            </div>
        </div>
        
    </div>
    
    <div class="row-fluid">
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                <img src="<?php echo $this->cubevizImagesPath; ?>semicon/measure2.png" 
                     style="width: 17px; margin-left: 10px;"/>
                     
                &nbsp; &nbsp;
                <?php echo $this->translate->_('AnalyzeAction_MeasureProperties'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->measureProperties); ?>
            </div>
        </div>
        
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    <img src="<?php echo $this->cubevizImagesPath; ?>semicon/attribute2.png" 
                         style="width: 17px; margin-left: 10px;"/>
                         
                    &nbsp; &nbsp; 
                    <?php echo $this->translate->_('AnalyzeAction_AttributeProperties'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->attributeProperties); ?>
            </div>
        </div>        
        
        
    </div>
    
    <div class="row-fluid">
        
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    <img src="<?php echo $this->cubevizImagesPath; ?>semicon/slice2.png" 
                         style="width: 17px; margin-left: 10px;"/>
                         
                    &nbsp; &nbsp;
                    <?php echo $this->translate->_('AnalyzeAction_Slices'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->slices); ?>
            </div>
        </div>
      
        <div class="span4 cubeviz-box">
            <div style="float:left;">
                <h3>
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <?php echo $this->translate->_('AnalyzeAction_SliceKeys'); ?></h3>
            </div>
                
            <div style="float:right; font-size: 29px;">
                <?php echo count ($this->sliceKeys); ?>
            </div>
        </div>
        
    </div>
    
    <hr/>
    
    <!-- Detailed information -->
    <div class="row-fluid">
        
        <div class="span5 cubeviz-box" style="min-width: 600px;">
            <h1>
                <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dataset2.png" 
                     style="width: 14px; vertical-align: middle;"/>
                &nbsp; Foobar</h1>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_DataStructureDefinitions'); ?></h3>
                
                sssss
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_Slices'); ?></h3>
                
                Foo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobar
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_AttributeProperties'); ?></h3>
                
                None found
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_MeasureProperties'); ?></h3>
                
                <a href="">Value</a>, another Value
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_Dimensions'); ?></h3>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, 
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
            </div>
        </div>
        
        <div class="span5 cubeviz-box" style="min-width: 600px;">
            <h1>
                <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dataset2.png" 
                     style="width: 14px; vertical-align: middle;"/>
                &nbsp; Foobar</h1>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_DataStructureDefinitions'); ?></h3>
                
                sssss
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_Slices'); ?></h3>
                
                Foo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobarFoo, Bar, foobar
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_AttributeProperties'); ?></h3>
                
                None found
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_MeasureProperties'); ?></h3>
                
                <a href="">Value</a>, another Value
            </div>
            
            <hr/>
            
            <div style="clear: both;">
                <h3 style="color: #999999;"><?php echo $this->translate->_('AnalyzeAction_Dimensions'); ?></h3>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, Germany, England, 
                    </div>
                </div>
                
                <div style="clear: both; padding-top: 5px;">
                    <div style="float: left;">
                        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/dimension.png" 
                             style="width: 10px; vertical-align: middle;"/>
                        &nbsp;
                        <a href="">Country</a></div>
                    <div style="float: right;">
                        Germany, England, ...
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
</div>
