<script type="text/javascript">
    cubeVizApp
        .add("View_CompareAction_ModelSelection", "")
        .add("View_CompareAction_DatasetSelection", "")
        .add("View_CompareAction_DimensionOverview", "");
</script>

<div class="" id="cubeviz-compare-container" style="" title="">

    <div class="row-fluid">
        
        <!-- 
            row 
        -->
        <div class="span12">
            
            <h2>Source Selection</h2>
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <h3>Choose model</h3>
                    
                    <i class="icon-lightbulb"></i>
                    <em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt massa dolor, eget sodales dui convallis ac.</em>
                    
                    <div class="row-fluid">
                        
                        <div class="span6">
                            <select id="cubeviz-compare-modelSelector1" name="" style="width: 220px; min-width: 220px;">
                                <option value="">- please select -</option>
                                
                                <?php foreach ($this->models as $model): ?>
                                    <option value="<?php echo $model ['uri']; ?>">
                                        <?php echo $model ['label']; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        
                        <div class="span6">
                            <select id="cubeviz-compare-modelSelector2" name="" style="width: 220px; min-width: 220px;">
                                <option value="">- please select -</option>
                                
                                <?php foreach ($this->models as $model): ?>
                                    <option value="<?php echo $model ['uri']; ?>">
                                        <?php echo $model ['label']; ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        
                    </div>
                </div>
                
                <!-- right -->
                <div class="span6"></div>
            </div>
            
            <!--  
                block 
            -->
            <div class="row-fluid" id="cubeviz-compare-datasetSelection">
                <!-- left -->
                <div class="span6">                    
                    
                    <h3>Choose dataset</h3>
                    
                    <i class="icon-lightbulb"></i>
                    <em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt massa dolor, eget sodales dui convallis ac.</em>
                    
                    <div class="row-fluid">
                        
                        <div class="span6">
                            <div class="" id="cubeviz-compare-datasetSelectionDiv1" name="" style="">
                                
                                <select id="cubeviz-compare-datasetSelector1"></select>
                                
                                <div class="cubeviz-compare-warningBox" id="cubeviz-compare-datasetSelectorWarningBox1" style="display: none;" title="">
                                    Selected model contains no datasets!
                                </div>
                            </div>
                        </div>
                        
                        <div class="span6">
                            <div class="" id="cubeviz-compare-datasetSelectionDiv2" name="" style="">
                                <select id="cubeviz-compare-datasetSelector2"></select>
                            </div>
                            
                            <div class="cubeviz-compare-warningBox" id="cubeviz-compare-datasetSelectorWarningBox2" style="display: none;" title="">
                                Selected model contains no datasets!
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <!-- right -->
                <div class="span6">
                    
                </div>
            </div>            
        </div>
    </div>
    
    <br/>
        
    <div class="row-fluid">
        <!--    
            row 
        -->
        <div class="span12">
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <div id="container" style="min-width: 400px; height: 650px; margin: 0 auto"></div>
                    
                    <script>
                        $(document).ready(function(){
                            $("#container").highcharts({
                                xAxis: {
                                    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                                },
                                series: [{
                                    name: 'Tokyo',
                                    data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
                                }]
                            });
                        });
                    </script>
                    
                </div>
                
                <!-- right -->
                <div class="span6">
                    
                    <strong>Data overview</strong>
                    
                    <br/>
                    <br/>
                    
                    <div style="height: 500px; overflow-y: auto; border-bottom: 1px solid #BFBFBF;">
                        <table class="table table-bordered">
                            <tr>
                                <td style="height: 70px;"><div style="-webkit-transform:rotate(-90deg);">Dimension Element 1</div></td>
                                <td><div style="-webkit-transform:rotate(-90deg);">Dimension Element 2</div></td>
                                <td colspan="2" style="text-align: center;">Value</td>
                                <!--
                                <td>Value 1</td>
                                <td>Value 2</td>
                                -->
                                <td><div style="-webkit-transform:rotate(-90deg);">Dimension Element 1</div></td>
                                <td><div style="-webkit-transform:rotate(-90deg);">Dimension Element 2</div></td>
                            </tr>
                            <tr>
                                <td>United States of America</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                            <tr>
                                <td>Germany</td>
                                <td>2010</td>
                                <td>0.45</td>
                                <td>0.70</td>
                                <td>2011</td>
                                <td>England</td>
                            </tr>
                        </table>
                    </div>
                    
                    
                    
                    <h3>Value Handling</h3>
                    
                    <!--  
                        block 
                    -->
                    <div class="row-fluid">
                        <!-- left -->
                        <div class="span6">
                            <table class="table table-bordered">
                                <tr>
                                    <td>Value 1</td>
                                </tr>
                            </table>
                        </div>
                        <!-- right -->
                        <div class="span6">
                            <table class="table table-bordered">
                                <tr>
                                    <td>Value 2</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>        
    </div>
    
    <br/>
        
    <div class="row-fluid">
        <!--    
            row 
        -->
        <div class="span12">
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <div class="" id="" style="text-align: center;" title="">
                    
                        <div class="btn" id="" style="" title="">
                            <img src="<?php echo $this->cubevizImagesPath; ?>bar_stacked.png" style="width: 30px;"/>
                        </div>            
                        
                        <div class="btn" id="" style="" title="">
                            <img src="<?php echo $this->cubevizImagesPath; ?>column.png" style="width: 30px;"/>
                        </div>  
                    
                    </div> 
                    
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>         
            
        </div>        
    </div>
    
    <br/>
        
    <div class="row-fluid">
        <!--    
            row 
        -->
        <div class="span12">
            
            <h2>Dimension Selection</h2>
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <div style="width: 100%; text-align: center;">
                        <h3>Dimension 1</h3>
                    </div>
                    
                    <table class="table table-bordered">
                        <tr>
                            <td>Dimension Element 3</td>
                            <td>Dimension Element 4</td>
                        </tr>
                    </table>
                    
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <div style="width: 100%; text-align: center;">
                        <h3>Dimension 1</h3>
                    </div>
                    
                    <table class="table table-bordered">
                        <tr class="success">
                            <td colspan="2" style="text-align: center;">Dimension Element 1</td>
                        </tr>
                        <tr class="success">
                            <td colspan="2" style="text-align: center;">Dimension Element 2</td>
                        </tr>
                        <tr>
                            <td>Dimension Element 3</td>
                            <td>Dimension Element 4</td>
                        </tr>
                    </table>
                    
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    <!--  
                        block 
                    -->
                    <div class="row-fluid">
                        <!-- left -->
                        <div class="span6">
                            <h3>Dimension 2</h3>
                        </div>
                        <!-- right -->
                        <div class="span6">
                            <h3>Dimension 3</h3>
                        </div>
                    </div>
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                <!-- left -->
                <div class="span6">
                    
                    <table class="table table-bordered">
                        <tr class="success">
                            <td colspan="2" style="text-align: center;">Dimension Element 1</td>
                        </tr>
                        <tr class="success">
                            <td colspan="2" style="text-align: center;">Dimension Element 2</td>
                        </tr>
                        <tr>
                            <td>Dimension Element 3</td>
                            <td>Dimension Element 4</td>
                        </tr>
                    </table>
                        
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                
                <!-- left -->
                <div class="span6">
                    <!--  
                        block 
                    -->
                    <div class="row-fluid">
                        <!-- left -->
                        <div class="span6">
                            
                            <h3>Dimension 4</h3>
                    
                            <table class="table table-bordered">
                                <tr>
                                    <td>Dimension Element 3</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 3</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 3</td>
                                </tr>
                            </table>                            
                            
                        </div>
                        <!-- right -->
                        <div class="span6">
                            <h3>Dimension 5</h3>
                    
                            <table class="table table-bordered">
                                <tr>
                                    <td>Dimension Element 5</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 5</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 5</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            
            <!--  
                block 
            -->
            <div class="row-fluid">
                
                <!-- left -->
                <div class="span6">
                    <!--  
                        block 
                    -->
                    <div class="row-fluid">
                        <!-- left -->
                        <div class="span6">
                            
                        
                        </div>
                        <!-- right -->
                        <div class="span6">
                            <h3>Dimension 6</h3>
                    
                            <table class="table table-bordered">
                                <tr>
                                    <td>Dimension Element 4</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 4</td>
                                </tr>
                                <tr>
                                    <td>Dimension Element 4</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                
                <!-- right -->
                <div class="span6">&nbsp;</div>
            </div>
            
            
        </div>        
    </div>
    
    <br/>

</div>
