<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.module.isLoaded = true;
    
    cubeVizApp
        .add("View_CubeVizModule_DataStructureDefintion", "#cubeviz-dataStructureDefinition-list")
        .add("View_CubeVizModule_DataSet", "#cubeviz-dataSet-list")
        .add("View_CubeVizModule_Component", "#cubviz-component-listBox")
        .add("View_CubeVizModule_Footer", "#cubeviz-footer-container");
</script>

<!-- 
    Left sidebar 
-->

<div id="cubeviz-module-spinner">
    <i class="icon-spinner icon-spin" style="vertical-align: middle;"></i>
    I am working ...
</div>

<div id="cubeviz-module-dataSelection">
    <!-- Data structure definition section -->
    <div id="cubviz-dataStructureDefinition-container">
        <div style="width: 100%; margin-bottom:2px;">
            <div class="cubeviz-label" style="float: left;">
                Select group of interest
            </div>
            <div style="float:right; padding-right:0.3em">
                <i class="icon-question-sign cubeviz-clickable"
                   id="cubeviz-dataStructureDefinition-questionMark"
                   title="Click for more information"></i>
            </div>
            <br/>
            <select name="cubeviz-dataStructureDefinition-list" 
                     id="cubeviz-dataStructureDefinition-list"></select>
        </div>
    </div>
    
    <!-- Data set section -->
    <div id="cubviz-dataSet-container">
        <div style="width: 100%; margin-bottom:2px;">
            <div class="cubeviz-label" style="float: left;">
                Select part of group
            </div>
            <div style="float:right;padding-right:0.3em">
                <i class="icon-question-sign cubeviz-clickable"
                   id="cubeviz-dataSet-questionMark"
                   title="Click for more information"></i>
            </div>                    
        </div>
        <select name="cubeviz-dataSet-list" id="cubeviz-dataSet-list"></select>
    </div>
    
    <!-- Visual seperator -->
    <div style="height: 1px; border:0; width:100%; margin-top: 6px; margin-bottom: 6px;"></div>
    
    <!-- Component section -->
    <div id="cubviz-component-container">
        <div style="width: 100%;">
            <div class="cubeviz-label" style="float: left;">
                Select axis elements
            </div>
            <div style="float:right;padding-right:0.3em">
                <i class="icon-question-sign cubeviz-clickable"
                   id="cubeviz-component-questionMark"
                   title="Click for more information"></i>
            </div>
        </div>
        <div style="clear: both;"></div>
        <div id="cubviz-component-listBox"></div>
    </div>
    
    <div id="cubeviz-footer-container">                
        <span style="float:left;">
            <a class="cubeviz-btn" id="cubeviz-footer-permaLinkButton">
                Permalink</a>
            <span id="cubeviz-footer-permaLinkMenu">
                <span id="cubeviz-footer-permaLink" style="display: none;">Link</span>
            </span>
        </span>
        <span style="float:right;">
            <a class="cubeviz-btn" id="cubeviz-footer-showVisualizationButton">
                Show Visualization</a>
        </span>
    </div>
</div>

<!-- 
    #########
    DIALOGS
    #########
-->
<div id="cubeviz-dataStructureDefinition-dialog" 
      style="display: none;"
      title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select group of interest</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        A group of interest contains data about a particular field of interest, for
        instance about countries. Following the structure given by the 
        <a href="http://www.w3.org/TR/vocab-data-cube/" target="_blank">DataCube vocabulary</a>, 
        users are able to select specific structural elements of the DataCube.
    </div>
</div>

<div id="cubeviz-dataSet-dialog" 
      style="display: none;"
      title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select part of group</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each structural element of a DataCube contains data sets. A data set is the
        major entity: it groups statistical data about a specific topic, called
        observations. 
    </div>
</div>

<div id="cubeviz-component-dialog" style="display: none;" title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
             src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select axis elements</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each data set contains statistical data. These data is a collection of so-called 
        observations. Under an observation you can picture a point in a room. This point
        has coordinates which locates him at a specific position in this room. In general 
        these coordinates are 3 dimensional: height, width and deep. In the DataCube context
        these coordinates are dimensions and it is possible to have more than these 3.
        But these dimension are not positions in a room, you may think, but could be 
        everything, like a scala of money (e.g. from 1000 EUR to 100.000 EUR).
    </div>
</div>

<div id="cubeviz-component-setupDialogContainer" style="display: none;">
    <!-- Will contain the dialogs for setup the dimensions -->
</div>

<!-- 
    #########
    Templates
    #########
-->
<!-- Component-Dimension -->
<div id="cubeviz-component-tpl-listBoxItem" style="display: none;">
    <div class="cubeviz-component-box" id="cubeviz-component-box-[[__cv_uri]]">    
        <h3>
            [[__cv_niceLabel]]&nbsp;
            <nobr>
                (<span class="cubeviz-component-selectedCount">[[selectedElementCount]]</span> 
                / [[elementCount]])
            </nobr>
        </h3>
        <a class="cubeviz-component-setupComponentOpener">
            Select elements of interest
        </a>        
    </div>
</div>

<!-- Dialogs -->
<div id="cubeviz-component-tpl-setupComponentDialog" style="display: none;">
    <div class="cubeviz-component-setupComponentDialog"
         id="cubeviz-component-setupComponentDialog-[[__cv_hashedUri]]"
         title="Select elements of interest">
         
        <div style="float:right">
            <img class="cubeviz-icon-unsized"
                  src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
        </div>
        
        <h3 style="margin-top: 0px;">[[__cv_niceLabel]]</h3>      
        
        <div class="cubeviz-component-sortButtons" style="float:right; vertical-align: middle;">
            Sort by: 
            <span class="cubeviz-btn">alphabet</span>
            &nbsp;
            <span class="cubeviz-btn">check status</span>
            &nbsp;
            <span class="cubeviz-btn" style="display:none;">observation count</span>
        </div>
        
        <span class="cubeviz-btn cubeviz-component-selectAllButton">
            Select all items</span>
        
        <span class="cubeviz-btn cubeviz-component-deselectButton">
            Deselect all items</span>
        
        <ul class="cubeviz-component-setupComponentElements"></ul>
        
        <div style="margin-top: 5px; float:right;">            
            <span class="cubeviz-btn cubeviz-component-cancel">Cancel</span>
            &nbsp;
            <span class="cubeviz-btn cubeviz-component-closeAndUpdate">
                <i class="icon-spinner icon-spin cubeviz-component-closeUpdateSpinner" 
                   style="display: none;"></i>
                &nbsp;
                Close and update visualization</span>
        </div>
    </div>
</div>

<div id="cubeviz-component-tpl-setupComponentElement" style="display: none;">
    <li>
        <input type="checkbox" name="[[__cv_uri]]"/>
        <span style="vertical-align: middle;" title="[[__cv_uri2]]">
            <span>[[__cv_niceLabel]]</span>
        </span>
    </li>
</div>
