<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.module.isLoaded = true;
    
    cubeVizApp
        .add("View_CubeVizModule_DataStructureDefintion", "#cubeviz-dataStructureDefinition-list")
        .add("View_CubeVizModule_Footer", "#cubeviz-footer-container")    
        .add("View_CubeVizModule_DataSet", "#cubeviz-dataSet-list")
        .add("View_CubeVizModule_Component", "#cubviz-component-listBox");
</script>

<!-- Selection data routine -->

<div id="wrapper"></div>

<div id="sidebar-left">
    <div id="sidebar-left-data-selection">
        
        <!-- 
        <div id="sidebar-left-loader">
            <div style="margin-top: 90px; height: 220px;">
                <img src="<?php echo $this->moduleUrl; ?>public/images/loader.gif"/>
                Loading ...
            </div>
        </div>
        -->
        
        <div id="sidebar-left-data-selection-wrapper">
            
            <br/>
            
            <!-- Data structure definition section -->
            <div id="cubviz-dataStructureDefinition-container">
                <div style="width: 100%; font-size: 12px; font-weight:bold; margin-bottom:2px;">
                    <?php echo $this->_translate->_('Select group of interest'); ?>
                    &nbsp;
                    <img src="<?php echo $this->cubevizImagesPath; ?>questionmark.png" 
                         class="cubeviz-icon-micro cubeviz-clickable"
                         id="cubeviz-dataStructureDefinition-questionMark"
                         title="<?php echo $this->_translate->_('Click for more information'); ?>"/>
                </div>
                <select name="cubeviz-dataStructureDefinition-list" 
                         id="cubeviz-dataStructureDefinition-list"></select>
            </div>
            
            <!-- Data set section -->
            <div id="cubviz-dataSet-container">
                <div style="width: 100%; float:left; font-size: 12px; font-weight:bold; margin-bottom:2px;">
                    <?php echo $this->_translate->_('Select part of group'); ?>
                    &nbsp;
                    <img src="<?php echo $this->cubevizImagesPath; ?>questionmark.png" 
                         class="cubeviz-icon-micro cubeviz-clickable"
                         id="cubeviz-dataSet-questionMark"
                         title="<?php echo $this->_translate->_('Click for more information'); ?>"/>
                </div>
                <select name="cubeviz-dataSet-list" id="cubeviz-dataSet-list"></select>
            </div>
            
            <!-- Visual seperator -->
            <div style="height: 1px; border:0; width:100%; margin-top: 6px; margin-bottom: 6px;"></div>
            
            <!-- Component section -->
            <div id="cubviz-component-container">
                <div style="width: 100%; font-size: 12px; font-weight: bold;">
                    <?php echo $this->_translate->_('Select axis elements'); ?>
                    &nbsp;
                    <img src="<?php echo $this->cubevizImagesPath; ?>questionmark.png" 
                         class="cubeviz-icon-micro cubeviz-clickable"
                         id="cubeviz-component-questionMark"
                         title="<?php echo $this->_translate->_('Click for more information'); ?>"/>
                </div>
                <div id="cubviz-component-listBox"></div>
            </div>
            
            <div id="cubeviz-footer-container">                
                <span style="float:left;">
                    <input class="minibutton submit"
                            id="cubeviz-footer-permaLinkButton"
                            type="button"
                            value="<?php echo $this->_translate->_('Permalink'); ?>"/>
                    <span id="cubeviz-footer-permaLinkMenu">
                        <span id="cubeviz-footer-permaLink">Link</span>
                    </span>
                </span>
                <span style="float:right;">
                    <input class="minibutton submit"
                            id="cubeviz-footer-showVisualizationButton"
                            type="button" 
                            value="<?php echo $this->_translate->_('Show Visualization'); ?>"/>
                </span>
            </div>
            
        </div>
    </div>
</div>

<!-- 
    #########
    DIALOGS
    #########
-->
<div id="cubeviz-dataStructureDefinition-dialog" 
      style="display: none;"
      title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h2>Select group of interest</h2>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        A group of interest contains data about a particular field of interest, for
        instance about countries. Following the structure given by the 
        <a href="http://www.w3.org/TR/vocab-data-cube/" target="_blank">DataCube vocabulary</a>, 
        users are able to select specific structural elements of the DataCube.
    </div>
</div>

<div id="cubeviz-dataSet-dialog" 
      style="display: none;"
      title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h2>Select part of group</h2>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each structural element of a DataCube contains data sets. A data set is the
        major entity: it groups statistical data about a specific topic, called
        observations. 
    </div>
</div>

<div id="cubeviz-component-questionMarkDialog" 
     style="display: none;"
     title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h2>Select axis elements</h2>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each data set contains statistical data. These data is a collection of so-called 
        observations. Under an observation you can picture a point in a room. This point
        has coordinates which locates him at a specific position in this room. In general 
        these coordinates are 3 dimensional: height, width and deep. In the DataCube context
        these coordinates are dimensions and it is possible to have more than these 3.
        But these dimension are not positions in a room, you may think, but could be 
        everything, like a scala of money (e.g. from 1000 EUR to 100.000 EUR).
    </div>
</div>

<div id="cubeviz-component-setupDialogContainer" style="display: none;">
    <!-- Will contain the dialogs for setup the dimensions -->
</div>

<!-- 
    #########
    Templates
    #########
-->
<!-- Data Structure Definition -->
<script id="cubeviz-dataStructureDefinition-tpl-listOption" type="text/template">
    <option value="<%= hashedUrl %>"<%= selected %>>
        <%= label %>
    </option>    
</script>

<!-- Data Set -->
<script id="cubeviz-dataSet-tpl-listOption" type="text/template">
    <option value="<%= hashedUrl %>"<%= selected %>>
        <%= label %>
    </option>    
</script>

<!-- Component-Dimension -->
<script id="cubeviz-component-tpl-listBoxItem" type="text/template">
    <div class="cubeviz-component-box" id="cubeviz-component-box-<%= hashedUrl %>">    
        <div class="cubeviz-component-title">
            <%= label %>&nbsp;
            <nobr>
                (<span class="cubeviz-component-selectedCount"><%= selectedElementCount %></span> 
                / <%= elementCount %>)
            </nobr>
        </div>
        <small>Explanation text</small>
        <br/>
        <a class="cubeviz-component-setupComponentOpener">
            <?php echo $this->_translate->_('Select elements of interest'); ?>
        </a>        
    </div>
</script>

<!-- Dialogs -->
<script id="cubeviz-component-tpl-setupComponentDialog" type="text/template">
    <div class="cubeviz-component-setupComponentDialog"
         id="cubeviz-component-setupComponentDialog-<%= hashedUrl %>"
         title="<?php echo $this->_translate->_('Select elements of interest'); ?>">
        <div style="margin-top: 4px; float: right;">
            <img class="cubeviz-icon-small"
                  src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
        </div>
        <div style="float: left;">
            <h2><%= label %></h2>
        </div>
        <br/>
        <br/>
        <div style="clear: both;">
            <p>Dimension Meta Information</p>
            <small>Hookline, whats possible here?</small>
            
            <ul class="cubeviz-component-setupComponentElements"></ul>
            
            <div style="float:left;">            
                <a class="cubeviz-component-setupComponentDeselectButton">
                    <?php echo $this->_translate->_('Deselect all items'); ?>
                </a>
            </div>
            
            <br/>
            
            <div class="cubeviz-component-setupComponentButton" style="float:right;">            
                <input class="cubeviz-component-cancel cubeviz-button cubeviz-clickable"
                        type="button"
                        value="<?php echo $this->_translate->_('Cancel'); ?>"/>
                
                &nbsp;&nbsp;&nbsp;
                
                <input class="cubeviz-component-closeAndUpdate cubeviz-button cubeviz-clickable"
                        type="button"
                        value="<?php echo $this->_translate->_('Close and update visualization'); ?>"/>
            </div>
        </div>
    </div>
</script>

<script id="cubeviz-component-tpl-setupComponentElement" type="text/template">
    <li>
        <input type="checkbox" name="<%= hashedProperty %>" value="<%= property %>"<%= checked %>/>
        <label><%= propertyLabel %></label>
    </li>
</script>
