<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.module.isLoaded = true;
    
    cubeVizApp
        .add("View_CubeVizModule_DataStructureDefintion", "#cubeviz-dataStructureDefinition-list")
        .add("View_CubeVizModule_Footer", "#cubeviz-footer-container")    
        .add("View_CubeVizModule_DataSet", "#cubeviz-dataSet-list")
        .add("View_CubeVizModule_Component", "#cubviz-component-listBox");
</script>

<!-- Selection data routine -->

<div id="wrapper"></div>

<div id="sidebar-left">
    <div id="sidebar-left-data-selection">
        
        <!-- 
        <div id="sidebar-left-loader">
            <div style="margin-top: 90px; height: 220px;">
                <img src="<?php echo $this->moduleUrl; ?>public/images/loader.gif"/>
                Loading ...
            </div>
        </div>
        -->
        
        <div id="sidebar-left-data-selection-wrapper">
            
            <br/>
            
            <!-- Data structure definition section -->
            <div id="cubviz-dataStructureDefinition-container">
                <div style="width: 100%; font-size: 12px; font-weight:bold; margin-bottom:2px;">
                    <div style="float: left;">
                        <?php echo $this->_translate->_('Select group of interest'); ?>
                    </div>
                    <div style="float: right;">
                        <i class="icon-question-sign cubeviz-clickable"
                           id="cubeviz-dataStructureDefinition-questionMark"
                           style="font-size: 14px; opacity:0.6; filter:alpha(opacity=60);"
                           title="<?php echo $this->_translate->_('Click for more information'); ?>"></i>
                    </div>
                    <select name="cubeviz-dataStructureDefinition-list" 
                             id="cubeviz-dataStructureDefinition-list"></select>
                </div>
            </div>
            
            <!-- Data set section -->
            <div id="cubviz-dataSet-container">
                <div style="width: 100%; font-size: 12px; font-weight:bold; margin-bottom:2px;">
                    <div style="float: left">
                        <?php echo $this->_translate->_('Select part of group'); ?>
                    </div>
                    <div style="float: right;">
                        <i class="icon-question-sign cubeviz-clickable"
                           id="cubeviz-dataSet-questionMark"
                           style="font-size: 14px; opacity:0.6; filter:alpha(opacity=60);"
                           title="<?php echo $this->_translate->_('Click for more information'); ?>"></i>
                    </div>                    
                </div>
                <select name="cubeviz-dataSet-list" id="cubeviz-dataSet-list"></select>
            </div>
            
            <!-- Visual seperator -->
            <div style="height: 1px; border:0; width:100%; margin-top: 6px; margin-bottom: 6px;"></div>
            
            <!-- Component section -->
            <div id="cubviz-component-container">
                <div style="width: 100%; font-size: 12px; font-weight: bold;">
                    <div style="float: left;">
                        <?php echo $this->_translate->_('Select axis elements'); ?>
                    </div>
                    <div style="float: right;">
                        <i class="icon-question-sign cubeviz-clickable"
                           id="cubeviz-component-questionMark"
                           style="font-size: 14px; opacity:0.6; filter:alpha(opacity=60);"
                           title="<?php echo $this->_translate->_('Click for more information'); ?>"></i>
                    </div>
                </div>
                <div style="clear: both;"></div>
                <div id="cubviz-component-listBox"></div>
            </div>
            
            <div id="cubeviz-footer-container">                
                <span style="float:left;">
                    <a class="cubeviz-btn" id="cubeviz-footer-permaLinkButton">
                        <?php echo $this->_translate->_('Permalink'); ?></a>
                    <span id="cubeviz-footer-permaLinkMenu">
                        <span id="cubeviz-footer-permaLink" style="display: none;">Link</span>
                    </span>
                </span>
                <span style="float:right;">
                    <a class="cubeviz-btn" id="cubeviz-footer-showVisualizationButton">
                        <strong><?php echo $this->_translate->_('Show Visualization'); ?></strong></a>
                </span>
            </div>
            
        </div>
    </div>
</div>

<!-- 
    #########
    DIALOGS
    #########
-->
<div id="cubeviz-dataStructureDefinition-dialog" 
      style="display: none;"
      title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select group of interest</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        A group of interest contains data about a particular field of interest, for
        instance about countries. Following the structure given by the 
        <a href="http://www.w3.org/TR/vocab-data-cube/" target="_blank">DataCube vocabulary</a>, 
        users are able to select specific structural elements of the DataCube.
    </div>
</div>

<div id="cubeviz-dataSet-dialog" 
      style="display: none;"
      title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select part of group</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each structural element of a DataCube contains data sets. A data set is the
        major entity: it groups statistical data about a specific topic, called
        observations. 
    </div>
</div>

<div id="cubeviz-component-dialog" 
     style="display: none;"
     title="<?php echo $this->_translate->_('Information'); ?>">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-small"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4>Select axis elements</h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        Each data set contains statistical data. These data is a collection of so-called 
        observations. Under an observation you can picture a point in a room. This point
        has coordinates which locates him at a specific position in this room. In general 
        these coordinates are 3 dimensional: height, width and deep. In the DataCube context
        these coordinates are dimensions and it is possible to have more than these 3.
        But these dimension are not positions in a room, you may think, but could be 
        everything, like a scala of money (e.g. from 1000 EUR to 100.000 EUR).
    </div>
</div>

<div id="cubeviz-component-setupDialogContainer" style="display: none;">
    <!-- Will contain the dialogs for setup the dimensions -->
</div>

<!-- 
    #########
    Templates
    #########
-->
<!-- Data Structure Definition -->
<script id="cubeviz-dataStructureDefinition-tpl-listOption" type="text/template">
    <option value="<%= hashedUrl %>"<%= selected %>>
        <%= label %>
    </option>    
</script>

<!-- Data Set -->
<script id="cubeviz-dataSet-tpl-listOption" type="text/template">
    <option value="<%= hashedUrl %>"<%= selected %>>
        <%= label %>
    </option>    
</script>

<!-- Component-Dimension -->
<script id="cubeviz-component-tpl-listBoxItem" type="text/template">
    <div class="cubeviz-component-box" id="cubeviz-component-box-<%= hashedUrl %>">    
        <div class="cubeviz-component-title">
            <%= label %>&nbsp;
            <nobr>
                (<span class="cubeviz-component-selectedCount"><%= selectedElementCount %></span> 
                / <%= elementCount %>)
            </nobr>
        </div>
        <a class="cubeviz-component-setupComponentOpener">
            <?php echo $this->_translate->_('Select elements of interest'); ?>
        </a>        
    </div>
</script>

<!-- Dialogs -->
<script id="cubeviz-component-tpl-setupComponentDialog" type="text/template">
    <div class="cubeviz-component-setupComponentDialog"
         id="cubeviz-component-setupComponentDialog-<%= hashedUrl %>"
         title="<?php echo $this->_translate->_('Select elements of interest'); ?>">
         
        <div style="float:right">
            <img class="cubeviz-icon-small"
                  src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
        </div>
        
        <h2 style="margin-top: 8px;"><%= label %></h2>      
        
        <br/>
        
        <div class="cubeviz-component-sortButtons" style="float:right; vertical-align: middle;">
            Sort by: 
            <span class="cubeviz-btn">alphabet</span>
            &nbsp;
            <span class="cubeviz-btn">check status</span>
            &nbsp;
            <span class="cubeviz-btn" style="display:none;">observation count</span>
        </div>
        
        <span class="cubeviz-btn cubeviz-component-selectAllButton">
            Select all items</span>
        
        <span class="cubeviz-btn cubeviz-component-deselectButton">
            Deselect all items</span>
        
        <ul class="cubeviz-component-setupComponentElements"></ul>
        
        <div style="margin-top: 5px; float:right;">            
            <span class="cubeviz-btn cubeviz-component-cancel">
                <?php echo $this->_translate->_('Cancel'); ?></span>
            &nbsp;
            <span class="cubeviz-btn cubeviz-component-closeAndUpdate">
                <?php echo $this->_translate->_('Close and update visualization'); ?></span>
        </div>
    </div>
</script>

<script id="cubeviz-component-tpl-setupComponentElement" type="text/template">
    <li>
        <input type="checkbox" name="<%= hashedUri %>" value="<%= uri %>"<%= checked %>/>
        <span style="vertical-align: middle;">
            <span style="font-size: 13px;"><%= label %></span>
        </span>
    </li>
</script>
