<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.dataselectionModule.isLoaded = true;
    
    cubeVizApp
        .add("View_CubeVizModule_DataSet", "#cubeviz-dataSet-list")
        .add("View_CubeVizModule_Component", "#cubviz-component-listBox")
        .add("View_CubeVizModule_Footer", "#cubeviz-footer-container");
</script>

<!-- 
    Left sidebar 
-->

<div id="cubeviz-module-spinner">
    <i class="icon-spinner icon-spin" style="vertical-align: middle;"></i>
    <?php echo $this->translate->_('DataSelectionModule_LoadingMessage'); ?>
</div>

<div id="cubeviz-module-dataSelection">
    
    <!-- Data set and slice section -->
    <div style="float: left; height: 50px; text-align: center;">
        <img src="<?php echo $this->cubevizImagesPath; ?>semicon/subgraph_dots2.png" 
             style="width: 15px; margin-top: 15px; margin-left: 10px;"
             title="<?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?>"/>
    </div>
    <div style="float: left; margin-left: 20px;">
        <select name="cubeviz-dataSet-list" id="cubeviz-dataSet-list"></select>
        <br/>
        <select style="min-width: 180px;"><option>Slice1</option></select>
    </div>
    
    <!-- Visual seperator -->
    <div class="cubeviz-module-visualSeparator"><hr/></div>
    
    
    <!-- Data set and slice section -->
    <div style="float: left; height: 55px; text-align: center;">
        <img src="<?php echo $this->cubevizImagesPath; ?>attributeAndMeasure.png" 
             style="width: 15px; margin-top: 15px; margin-left: 10px;"
             title="<?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?>"/>
    </div>
    <div style="float: left; margin-left: 20px;">
        <select style="width: 170px; min-width: 180px;"><option>Attribute1</option></select>
        <br/>
        <select style="width: 170px; min-width: 180px;"><option>Measure1</option></select>
    </div>
    
    <!-- Visual seperator -->
    <div class="cubeviz-module-visualSeparator"><hr/></div>
    
    
    <!-- Component section -->
    <div id="cubviz-component-container">
        <div id="cubviz-component-listBox"></div>
    </div>
    
    <!-- Visual seperator -->
    <div class="cubeviz-module-visualSeparator"><hr/></div>
    
    
    <div id="cubeviz-footer-container">                
        <span>
            <a class="cubeviz-btn" 
               id="cubeviz-footer-permaLinkButton"
               style="font-size: 12.5px;">
                <i class="icon-pushpin" style="font-size: 11px;"></i>
                <?php echo $this->translate->_('DataSelectionModule_Permalink'); ?></a>
            <span id="cubeviz-footer-permaLinkMenu">
                <span id="cubeviz-footer-permaLink" style="display: none;">
                    <?php echo $this->translate->_('DataSelectionModule_Link'); ?></span>
            </span>
        </span>
        <span style="float:right;">
            <a class="cubeviz-btn" 
               id="cubeviz-footer-showVisualizationButton"
               style="font-size: 12.5px;">
                <i class="icon-refresh" style="font-size: 11px;"></i>
                <?php echo $this->translate->_('DataSelectionModule_ShowVisualization'); ?></a>
        </span>
    </div>
</div>

<!-- 
    #########
    DIALOGS
    #########
-->
<div id="cubeviz-dataSet-dialog" 
      style="display: none;"
      title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4><?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?></h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        <?php echo $this->translate->_('DataSelectionModule_SelectDSHelpText'); ?></div>
</div>

<div id="cubeviz-component-dialog" style="display: none;" title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
             src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4><?php echo $this->translate->_('DataSelectionModule_SelectComponents'); ?></h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        <?php echo $this->translate->_('DataSelectionModule_SelectComponentsHelpText'); ?></div>
</div>

<div id="cubeviz-component-setupDialogContainer" style="display: none;">
    <!-- Will contain the dialogs for setup the dimensions -->
</div>

<!-- 
    #########
    Templates
    #########
-->
<!-- Component-Dimension -->
<div id="cubeviz-component-tpl-listBoxItem" style="display: none;">
    <div class="cubeviz-component-box" id="cubeviz-component-box-[[__cv_uri]]">            
        <div style="float: left; height: 50px; width: 20px; text-align: center;">
            <img src="<?php echo $this->cubevizImagesPath; ?>semicon/center.png" 
                 style="width: 15px; margin-left: 10px; padding-top: 4px;"
                 title="<?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?>"/>
            
            <br/>
                        
        </div>
        <div style="float: left; width: 180px; height: 50px; padding-left: 20px;">
            
            <span style="font-size: 14.5px;">[[__cv_niceLabel]]</span>
            <span style="color: #AFAFAF; font-size: 11px;">
                <span class="cubeviz-component-selectedCount">[[__cv_selectedElementCount]]</span>
                <?php echo $this->translate->_('DataSelectionModule_Of'); ?> 
                [[__cv_elementCount]]
                <?php echo $this->translate->_('DataSelectionModule_Selected'); ?> 
            </span>
            
            <br/>
            <span style="color: #AFAFAF; font-size: 11px;">
                This is 
            </span>
            
        </div>
        <div style="float: left; width: 20px; min-width: 20px; height: 50px; text-align: right; padding-top: 4px;">
            <i class="icon-cogs cubeviz-clickable cubeviz-component-setupComponentOpener"
               title="<?php echo $this->translate->_('DataSelectionModule_SelectComponentElements'); ?>"></i>
        </div>
    </div>
</div>

<!-- Dialogs -->
<div id="cubeviz-component-tpl-setupComponentDialog" style="display: none;">
    <div class="cubeviz-component-setupComponentDialog"
         id="cubeviz-component-setupComponentDialog-[[__cv_hashedUri]]"
         title="Select elements of interest">
         
        <div style="float:right">
            <img class="cubeviz-icon-unsized"
                  src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
        </div>
        
        <h3 style="margin-top: 0px;">[[__cv_niceLabel]]</h3>
        
        <br/>
        <div style="clear: both;"></div>    
        
        <div class="cubeviz-component-sortButtons" style="float:right; vertical-align: middle;">
            <?php echo $this->translate->_('DataSelectionModule_SortBy'); ?>: 
            
            <span class="cubeviz-btn">
                <?php echo $this->translate->_('DataSelectionModule_Alphabet'); ?></span>
            &nbsp;
            <span class="cubeviz-btn">
                <?php echo $this->translate->_('DataSelectionModule_CheckStatus'); ?></span>
            &nbsp;
            <span class="cubeviz-btn" style="display:none;">
                <?php echo $this->translate->_('DataSelectionModule_ObservationCount'); ?></span>
        </div>
        
        <span class="cubeviz-btn cubeviz-component-selectAllButton">
            <?php echo $this->translate->_('DataSelectionModule_SelectAllItems'); ?></span>
        
        <span class="cubeviz-btn cubeviz-component-deselectButton">
            <?php echo $this->translate->_('DataSelectionModule_DeselectAllItems'); ?></span>
        
        <ul class="cubeviz-component-setupComponentElements"></ul>
        
        <div style="margin-top: 5px; float:right;">            
            <span class="cubeviz-btn cubeviz-component-cancel"><?php echo $this->translate->_('DataSelectionModule_Cancel'); ?></span>
            &nbsp;
            <span class="cubeviz-btn cubeviz-component-closeAndUpdate">
                <i class="icon-spinner icon-spin cubeviz-component-closeUpdateSpinner" 
                   style="display: none;"></i>
                &nbsp;
                <?php echo $this->translate->_('DataSelectionModule_CloseAndUpdateVisz'); ?></span>
        </div>
    </div>
</div>

<div id="cubeviz-component-tpl-setupComponentElement" style="display: none;">
    <li>
        <input type="checkbox" name="[[__cv_uri]]"/>
        <span style="vertical-align: middle;" title="[[__cv_uri2]]">
            <span>[[__cv_niceLabel]]</span>
        </span>
    </li>
</div>
