<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.dataselectionModule.isLoaded = true;
    
    cubeVizApp
        .add("View_CubeVizModule_DataSet", "#cubeviz-dataSet-list")
        .add("View_CubeVizModule_Component", "#cubviz-component-listBox")
        .add("View_CubeVizModule_Footer", "#cubeviz-footer-container");
</script>

<!-- 
    Left sidebar 
-->

<div id="cubeviz-module-spinner">
    <i class="icon-spinner icon-spin" style="vertical-align: middle;"></i>
    <?php echo $this->translate->_('DataSelectionModule_LoadingMessage'); ?>
</div>

<div id="cubeviz-module-dataSelection">
        
    <!-- Data set section -->
    <div id="cubviz-dataSet-container">
        <div style="width: 100%; margin-bottom:2px;">
            <div class="cubeviz-label" style="float: left;">
                <?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?></div>
            <div style="float:right;padding-right:0.3em">
                <i class="icon-question-sign cubeviz-clickable"
                   id="cubeviz-dataSet-questionMark"
                   title="<?php echo $this->translate->_('DataSelectionModule_ClickMoreInformation'); ?>"></i>
            </div>                    
        </div>
        <div>
            <select name="cubeviz-dataSet-list" id="cubeviz-dataSet-list"></select>
        </div>
    </div>
    
    <!-- Visual seperator -->
    <div style="height: 1px; border:0; width:100%; margin-top: 6px; margin-bottom: 6px;"></div>
    
    <!-- Component section -->
    <div id="cubviz-component-container">
        <div style="width: 100%;">
            <div class="cubeviz-label" style="float: left;">
                <?php echo $this->translate->_('DataSelectionModule_SelectComponents'); ?></div>
            <div style="float:right;padding-right:0.3em">
                <i class="icon-question-sign cubeviz-clickable"
                   id="cubeviz-component-questionMark"
                   title="<?php echo $this->translate->_('DataSelectionModule_ClickMoreInformation'); ?>"></i>
            </div>
        </div>
        <div style="clear: both;"></div>
        <div id="cubviz-component-listBox"></div>
    </div>
    
    <div id="cubeviz-footer-container">                
        <span>
            <a class="cubeviz-btn" id="cubeviz-footer-permaLinkButton">
                <?php echo $this->translate->_('DataSelectionModule_Permalink'); ?></a>
            <span id="cubeviz-footer-permaLinkMenu">
                <span id="cubeviz-footer-permaLink" style="display: none;">
                    <?php echo $this->translate->_('DataSelectionModule_Link'); ?></span>
            </span>
        </span>
        <span style="float:right;">
            <a class="cubeviz-btn" id="cubeviz-footer-showVisualizationButton">
                <?php echo $this->translate->_('DataSelectionModule_ShowVisualization'); ?></a>
        </span>
    </div>
</div>

<!-- 
    #########
    DIALOGS
    #########
-->
<div id="cubeviz-dataSet-dialog" 
      style="display: none;"
      title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
              src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4><?php echo $this->translate->_('DataSelectionModule_SelectDS'); ?></h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        <?php echo $this->translate->_('DataSelectionModule_SelectDSHelpText'); ?></div>
</div>

<div id="cubeviz-component-dialog" style="display: none;" title="Information">
    <div style="margin-top: 4px; float: right;">
        <img class="cubeviz-icon-unsized"
             src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <div style="float: left;">
        <h4><?php echo $this->translate->_('DataSelectionModule_SelectComponents'); ?></h4>
    </div>
    <br/>
    <br/>
    <div style="clear: both;">
        <?php echo $this->translate->_('DataSelectionModule_SelectComponentsHelpText'); ?></div>
</div>

<div id="cubeviz-component-setupDialogContainer" style="display: none;">
    <!-- Will contain the dialogs for setup the dimensions -->
</div>

<!-- 
    #########
    Templates
    #########
-->
<!-- Component-Dimension -->
<div id="cubeviz-component-tpl-listBoxItem" style="display: none;">
    <div class="cubeviz-component-box" id="cubeviz-component-box-[[__cv_uri]]">    
        <h3>
            [[__cv_niceLabel]]&nbsp;
            <nobr>
                (<span class="cubeviz-component-selectedCount">[[selectedElementCount]]</span> 
                / [[elementCount]])
            </nobr>
        </h3>
        <a class="cubeviz-component-setupComponentOpener">
            <?php echo $this->translate->_('DataSelectionModule_SelectComponentElements'); ?>
        </a>        
    </div>
</div>

<!-- Dialogs -->
<div id="cubeviz-component-tpl-setupComponentDialog" style="display: none;">
    <div class="cubeviz-component-setupComponentDialog"
         id="cubeviz-component-setupComponentDialog-[[__cv_hashedUri]]"
         title="Select elements of interest">
         
        <div style="float:right">
            <img class="cubeviz-icon-unsized"
                  src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
        </div>
        
        <h3 style="margin-top: 0px;">[[__cv_niceLabel]]</h3>
        
        <br/>
        <div style="clear: both;"></div>    
        
        <div class="cubeviz-component-sortButtons" style="float:right; vertical-align: middle;">
            <?php echo $this->translate->_('DataSelectionModule_SortBy'); ?>: 
            
            <span class="cubeviz-btn">
                <?php echo $this->translate->_('DataSelectionModule_Alphabet'); ?></span>
            &nbsp;
            <span class="cubeviz-btn">
                <?php echo $this->translate->_('DataSelectionModule_CheckStatus'); ?></span>
            &nbsp;
            <span class="cubeviz-btn" style="display:none;">
                <?php echo $this->translate->_('DataSelectionModule_ObservationCount'); ?></span>
        </div>
        
        <span class="cubeviz-btn cubeviz-component-selectAllButton">
            <?php echo $this->translate->_('DataSelectionModule_SelectAllItems'); ?></span>
        
        <span class="cubeviz-btn cubeviz-component-deselectButton">
            <?php echo $this->translate->_('DataSelectionModule_DeselectAllItems'); ?></span>
        
        <ul class="cubeviz-component-setupComponentElements"></ul>
        
        <div style="margin-top: 5px; float:right;">            
            <span class="cubeviz-btn cubeviz-component-cancel"><?php echo $this->translate->_('DataSelectionModule_Cancel'); ?></span>
            &nbsp;
            <span class="cubeviz-btn cubeviz-component-closeAndUpdate">
                <i class="icon-spinner icon-spin cubeviz-component-closeUpdateSpinner" 
                   style="display: none;"></i>
                &nbsp;
                <?php echo $this->translate->_('DataSelectionModule_CloseAndUpdateVisz'); ?></span>
        </div>
    </div>
</div>

<div id="cubeviz-component-tpl-setupComponentElement" style="display: none;">
    <li>
        <input type="checkbox" name="[[__cv_uri]]"/>
        <span style="vertical-align: middle;" title="[[__cv_uri2]]">
            <span>[[__cv_niceLabel]]</span>
        </span>
    </li>
</div>
