<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.index.isLoaded = true;
    
    // ui settings to adapt user interface
    cubeVizApp._.backend.uiSettings.useDataSetInsteadOfModel = <?php echo $this->uiUseDataSetInsteadOfModel; ?>;
    
    cubeVizApp
        .add("View_IndexAction_Header", "#cubeviz-index-headerDialogBox")
        .add("View_IndexAction_Visualization", "#cubeviz-index-visualization")
        .add("View_IndexAction_VisualizationSelector", "#cubeviz-visualizationselector-menuItems")
        .add("View_IndexAction_Legend", "")
        .add("View_IndexAction_ExportArea", "");
</script>

<div style="margin-left: 6px; margin-top: 10px;">
    
    <!-- Visualization selector -->
    <div style="float: right;">
        <div id="cubeviz-visualizationselector-selector"></div>
    </div>
    
    <!-- Header -->
    <div id="cubeviz-index-headerContainer" style="float: left;">
        <h2 id="cubeviz-index-header"></h2>
        <div id="cubeviz-index-headerSubheadline"></div>
    </div>
    
    <div style="clear: both;"></div>

    <!-- Visualization -->
    <div id="cubeviz-index-visualization"></div>
    
    <!-- Export area -->
    <?php if (true === $this->useExport) { ?>
    <div id="cubeviz-index-exportArea">
        <strong><?php echo $this->translate->_('IndexAction_ExportAs'); ?></strong>
        
        &nbsp;
        
        <a id="cubeviz-index-exportArea-btnTurtle"
           title="<?php echo $this->translate->_('IndexAction_ExportAsTurtle'); ?>">
            <img src="<?php echo $this->cubevizImagesPath; ?>semicon/turtle.png"
                 style="width: 20px;"/></a>
        
        &nbsp; 
        
        <a id="cubeviz-index-exportArea-btnCsv"
           title="<?php echo $this->translate->_('IndexAction_ExportAsCsv'); ?>">
            <img src="<?php echo $this->cubevizImagesPath; ?>semicon/csv2.png"
                 style="width: 17px;"/></a>
    </div>
    <?php } ?>

    <!-- Legend part -->
    <div id="cubeviz-index-legend">
        
        <span style="vertical-align: middle;">
            <strong><?php echo $this->translate->_('IndexAction_ShowInformationAbout'); ?></strong> &nbsp;
        </span>
        
        <!-- Information about the components -->
        <a class="cubeviz-btn" id="cubeviz-legend-btnShowSelectedConfiguration">
            <i class="icon-chevron-down"></i> &nbsp;
            <?php echo $this->translate->_('IndexAction_SelectedConfiguration'); ?></a>
        
        &nbsp;
        
        <!-- Information about the observations itself -->
        <a class="cubeviz-btn" id="cubeviz-legend-btnShowRetrievedObservations">
            <i class="icon-chevron-down"></i> &nbsp;
            <?php echo $this->translate->_('IndexAction_RetrievedData'); ?></a>
        
        <!-- Selected configuration -->
        <div id="cubeviz-legend-selectedConfiguration" style="display: none;">
            <br/>
            <h2><?php echo $this->translate->_('IndexAction_InformationAboutConfiguration'); ?></h2>
            
            <div id="cubeviz-legend-dsdAndDs"></div>
            <div id="cubeviz-legend-components"></div>
        </div>
        
        <!-- Retrieved observations -->
        <div id="cubeviz-legend-retrievedObservations" style="display: none; clear: both;">
            <br/>
            <h2><?php echo $this->translate->_('IndexAction_InformationAboutRetrievedData'); ?></h2>
            
            <table class="table table-bordered table-striped responsive-utilities" 
                   id="cubeviz-legend-observations"></table>
            <!--<div style="float: right; margin-right: 10px;">
                <p>
                    <a class="cubeviz-btn" id="cubeviz-legend-sortByTitle">
                        <?php echo $this->translate->_('IndexAction_SortByTitle'); ?></a>
                    <a class="cubeviz-btn" id="cubeviz-legend-sortByValue">
                        <?php echo $this->translate->_('IndexAction_SortByValue'); ?></a>
                </p>
            </div>-->
        </div>
    </div>
    
    <div style="clear: both;"></div>

    <!-- Visualization selector > menu + dongle -->    
    <div id="cubeviz-visualizationselector-menu">
        
        <h4><?php echo $this->translate->_('IndexAction_ConfigureVisualization'); ?></h4>
        
        <div id="cubeviz-visualizationselector-menuItems"></div>
        <br/>
        <br/>
        <br/>
        <div style="clear:both; text-align:right;">
            <a class="cubeviz-btn"
               id="cubeviz-visualizationselector-closeMenu"
               title="<?php echo $this->translate->_('IndexAction_CloseMenuWithoutApplyingChanges'); ?>">
                <?php echo $this->translate->_('IndexAction_Close'); ?>
            </a>
            
            <a class="cubeviz-btn"
               id="cubeviz-visualizationselector-updateVisz"
               title="<?php echo $this->translate->_('IndexAction_UpdateVisualizationBasedSettings'); ?>">
                <strong><?php echo $this->translate->_('IndexAction_Update'); ?></strong>
            </a>
        </div>
    </div>
    <div class="cubeviz-clickable" id="cubeviz-visualizationselector-menuDongleDiv">
        <img src="<?php echo $this->cubevizImagesPath; ?>menuDongle.png"
             style="width: 25px; height: 5px;"/>
    </div>
</div>

<div id="cubeviz-index-headerDialogBox"></div>


<!-- 
    TEMPLATES (text/template)
-->

<!-- 
    Header
-->
<div id="cubeviz-index-tpl-header" style="display: none;">
    [[modelLabel]]
</div>
<div id="cubeviz-index-tpl-headerSubheadline" style="display: none;">
    [[selectedDataSet]]
</div>
<div id="cubeviz-index-tpl-headerSubheadlineButtons" style="display: none;">
    &nbsp;
    &nbsp;
    <i class="icon-table"></i>
    <a href="#cubeviz-index-legend">
        <?php echo $this->translate->_('IndexAction_JumpToLegend'); ?></a>
    &nbsp;
    &nbsp;
    <i class="icon-lightbulb"></i>
    <a class="cubeviz-clickable"
       id="cubeviz-index-headerQuestionMarkHeadline"
       title="<?php echo $this->translate->_('IndexAction_ClickMoreInformation'); ?>"><?php echo $this->translate->_('IndexAction_ShowMetaData'); ?></a>
</div>

<!-- 
    Visualization selection menu 
-->
<div id="cubeviz-visualizationselector-tpl-selectorItem" style="display: none;">
    <a class="btn cubeviz-visualizationselector-selectorItem">
        <img class="cubeviz-icon-small" src=""/>
    </a>
</div>

<div id="cubeviz-visualizationselector-tpl-menuItem" style="display: none;">
    <div class="cubeviz-visualizationselector-menuItem" style="clear:both;">
        <div style="float:left; margin-left:3px;">[[label]]</div>
        <div style="float:right">
            <select class="cubeviz-visualizationselector-menuSelectbox cubeviz-visualizationselector-menuItemValue"></select>
        </div>
    </div>
</div>

<!-- 
    Dialog box for questionmark in headline (cubeviz-index-headerDialogBox) 
-->
<div id="cubeviz-index-tpl-headerDialogBoxHead" style="display: none;">
    <div style="margin-top: 4px; float: right; clear: both;">
        <img class="cubeviz-icon-unsized"
             src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <h4>Metadata about the dataset "[[label]]"</h4>
    <ul id="cubeviz-index-headerDialogBoxModelInformation"></ul>
</div>

<div id="cubeviz-index-tpl-headerDialogBoxEntry" style="display: none;">
    <li class="cubeviz-index-headerDialogBoxEntry">
        <strong>[[predicateLabel]]</strong>
        <div class="cubeviz-index-headerDialogBoxEntryContent">
            [[objectContent]]</div>
    </li>
</div>

<!-- 
    notification if no data were received
-->
<div id="cubeviz-visualization-tpl-nothingFoundNotification" style="display: none;">      
    <div id="cubeviz-visualization-nothingFoundNotification" align="center">
        <h4>
            <?php echo $this->translate->_('IndexAction_NotificationNoDataFitsSelection'); ?></h4>
        <br/>            
        <div style="width: 50%; text-align: left;">
            <div style="float:left;"><i class="icon-lightbulb"></i></div>
            <div style="margin-left: 24px;">
                <strong><?php echo $this->translate->_('IndexAction_Explanation'); ?></strong>
                <p>
                    <?php echo $this->translate->_('IndexAction_NotificationNoDataFitsSelectionExplanation'); ?>
                </p>
            </div>
        </div>
    </div>
</div>

<!-- 
    notification if highcharts.com #10 exception appears
-->
<div id="cubeviz-visualization-tpl-notificationHightchartsException10" style="display: none;">
    <div align="center">
        <div id="cubeviz-visualization-notificationHightchartsException10">
            <h4><?php echo $this->translate->_('IndexAction_NotificationHighChartsException10'); ?></h4>
        </div>
    </div>
</div>

<!--
    Legend
-->
<div id="cubeviz-legend-tpl-dsdAndDs" style="display: none;">
    <h3>
        <a href="[[dsdUrl]]" target="_blank">[[dsdLabel]]</a> -
        <a href="[[dsUrl]]" target="_blank">[[dsLabel]]</a>
    </h3>
</div>

<div id="cubeviz-legend-tpl-tableHeadEntry" style="display: none;">
    <h4>
        <a href="[[__cv_uri]]" target="_blank">[[__cv_niceLabel]]</a>
        &nbsp;&nbsp;
        <i class="cubeviz-legend-sortAsc icon-sort-by-attributes" 
           title="sort ascending"></i>
        &nbsp;
        <i class="cubeviz-legend-sortDesc icon-sort-by-attributes-alt" 
           title="sort descending"></i>
    </h4>
</div>

<div id="cubeviz-legend-tpl-observation" style="display: none;">
    <li>
        <span class="cubeviz-legend-observationIcon">
            <i class="icon-map-marker"></i>
        </span>
        <span>
            <span class="cubeviz-legend-observationLabel">[[__cv_niceLabel]]</span>
            
            <span class="cubeviz-legend-observationValue">[[__cv_value]]</span>
            
            <div style="height: 5px;"></div>
            
            <a href="[[__cv_uri]]" target="_blank">
                <?php echo $this->translate->_('IndexAction_GoToSource'); ?></a>
            
            <div style="height: 10px;"></div>
            
            <!-- Related dimension elements -->
            <ul class="cubeviz-legend-observationInfoList"></ul>
        </span>
    </li>
</div>


<div id="cubeviz-legend-tpl-observationInfoListEntry" style="display: none;"> 
    <li class="cubeviz-legend-observationInfoListEntry">
        <strong>[[dimensionLabel]]:</strong>
        <a href="[[__cv_uri]]" target="_blank" title="[[fullLabel]]">
            [[__cv_shortLabel]]</a>
    </li>
</div>


<div id="cubeviz-legend-tpl-componentList" style="display: none;"> 
    <ul id="cubeviz-legend-componentList"></ul>
</div>

<div id="cubeviz-legend-tpl-componentDimension" style="display: none;"> 
    <li class="cubeviz-legend-componentDimensionListEntry">
        <h3>[[__cv_niceLabel]]</h3>
        <ul class="cubeviz-legend-componentDimensionList"></ul>
    </li>
</div>

<div id="cubeviz-legend-tpl-componentDimensionEntry" style="display: none;"> 
    <li class="cubeviz-legend-componentDimensionEntry">        
        <span class="cubeviz-legend-componentDimensionIcon">
            <i class="icon-leaf" style="font-size: 11px;"></i>
        </span>
        <span>
            <h4 title="[[fullLabel]]">
                [[__cv_shortLabel]]</h4>
            <div style="height: 8px;"></div>
            <a class="cubeviz-legend-componentDimensionShowInfo">
                <?php echo $this->translate->_('IndexAction_ShowMoreInformation'); ?></a>
            <i class="icon-lightbulb cubeviz-clickable"></i>
            &nbsp;
            &nbsp;
            <a href="[[__cv_uri]]" target="_blank">
                <?php echo $this->translate->_('IndexAction_GoToSource'); ?></a>
        </span>
    </li>
</div>

<!-- 
    Dialog box for questionmark in headline(cubeviz-Index-questionMarkHeadline) 
-->
<div id="cubeviz-legend-componentDimensionInfoDialog"></div>

<div id="cubeviz-legend-tpl-componentDimensionInfoHeader" style="display: none;">
    <div style="float: right;">
        <img class="cubeviz-icon-unsized"
             src="<?php echo $this->cubevizImagesPath; ?>cubevizLogo.png"/>
    </div>
    <h5><?php echo $this->translate->_('IndexAction_MetaDataAboutDimensionElement'); ?> "[[__cv_niceLabel]]"</h5>
</div>

<div id="cubeviz-legend-tpl-componentDimensionInfoList" style="display: none;">
    <ul class="cubeviz-legend-componentDimensionInfoList"></ul>
</div>

<div id="cubeviz-legend-tpl-componentDimensionInfoListEntry" style="display: none;"> 
    <li>
        <br/>
        <strong>[[key]]</strong>
        <br/>
        [[value]]
    </li>
</div>


