<!-- 
    Dialog box for questionmark in headline(cubeviz-Index-questionMarkHeadline) 
-->
<div id="cubeviz-Index-DialogboxHeadline">
    
    <!-- Label -->
    <h2><?php echo $this->modelInformation ['rdfs:label']; ?></h2>
    
    <!-- Short description -->
    <div style="font-size: 14px;"><?php echo $this->modelInformation ['doap:shortdesc']; ?></div>
        
    <!-- Description -->
    <small><?php echo $this->modelInformation ['dc:description']; ?></small>
    
    <br/>
    <br/>
    <div style="font-size: 14px;">Information:</div>
    
    <ul class="cubeviz-ul-basic">
        <!-- Creator -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>person-pencil.png" class="cubeviz-icon-minimal" title="Creator"/>
            <?php echo $this->modelInformation ['dc:creator']; ?>
        </li>
    
        <!-- Revision -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>version2.png" class="cubeviz-icon-minimal" title="Revision"/>
            Revision: <?php echo $this->modelInformation ['doap:revision']; ?>
        </li>
    
        <!-- Document -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>document.png" class="cubeviz-icon-minimal" title="License"/>
            <?php echo $this->modelInformation ['doap:license']; ?>
        </li>
    </ul>
</div>
