<script type="text/javascript">
    
    cubeVizApp._.backend.uiParts.index.isLoaded = true;
    
    cubeVizApp
        .add("View_IndexAction_Header", "")
        .add("View_IndexAction_Visualization", "#cubeviz-index-visualization")
        .add("View_IndexAction_VisualizationSelector", "#cubeviz-visualizationselector-menuItems");
</script>

<div style="margin-left: 6px; margin-top: 10px;">
    <!-- Header -->
    <h2 id="cubeviz-index-header">
        CubeViz - Visualization of the <?php echo $this->CubeViz_ModelInformation['rdfs:label']; ?>
        &nbsp;
        <img class="cubeviz-icon-small"
              id="cubeviz-index-headerQuestionMarkHeadline" 
              src="<?php echo $this->cubevizImagesPath; ?>i.png" 
              title="<?php echo $this->_translate->_('Click for more information'); ?>"/>
    </h2>

    <!-- Visualization -->
    <div id="cubeviz-index-visualization"></div>

    <!-- Legend part -->
    <div id="cubeviz-index-legend"></div>

    <!-- Visualization selector -->
    <div id="cubeviz-visualizationselector-selector"></div>

    <!-- Visualization selector > menu + dongle -->    
    <div id="cubeviz-visualizationselector-menu">
        
        <div id="cubeviz-visualizationselector-menuHeader">
            <?php echo $this->_translate->_('Configure the visualization'); ?>
        </div>
        
        <div id="cubeviz-visualizationselector-menuItems"></div>
        <br/>
        <br/>
        <div style="clear:both; text-align:right;">
            <input class="cubeviz-minibutton cubeviz-clickable"
                    id="cubeviz-visualizationselector-closeMenu"
                    title="<?php echo $this->_translate->_('Close this menu without apply changes'); ?>"
                    type="button" 
                    value="<?php echo $this->_translate->_('Close'); ?>">
            &nbsp;&nbsp;&nbsp;
            <input class="cubeviz-minibutton cubeviz-clickable"
                    id="cubeviz-visualizationselector-updateVisz"
                    style="font-weight: bold;"
                    title="<?php echo $this->_translate->_('Update visualization based on new settings'); ?>"
                    type="button" 
                    value="<?php echo $this->_translate->_('Update'); ?>">
        </div>
    </div>
    <div id="cubeviz-visualizationselector-menuDongleDiv" class="cubeviz-clickable">
        <img id="cubeviz-visualizationselector-menuDongleImg" 
              src="<?php echo $this->cubevizImagesPath; ?>menuDongle.png"/>
    </div>
</div>

<!-- 
    Visualization selection menu 
-->
<script id="cubeviz-visualizationselector-tpl-selectorItem" type="text/template">
    <div class="cubeviz-visualizationselector-selectorItem cubeviz-clickable">
        <img class="cubeviz-icon-normal" 
             src="<?php echo $this->cubevizImagesPath; ?><%= icon %>"/>
    </div>
</script>

<script id="cubeviz-visualizationselector-tpl-menuItem" type="text/template">
    <div class="cubeviz-visualizationselector-menuItem" style="clear:both;">
        <div style="float:left; margin-left:3px; font-size:12px;"><%= label %></div>
        <div style="float:right">
            <select class="cubeviz-visualizationselector-menuSelectbox"></select>
        </div>
    </div>
</script>

<!-- 
    
-->
<div id="cubeviz-visualization-nothingFoundNotificationContainer">
    <div id="cubeviz-visualization-nothingFoundBox">
        <div align="center">        
            <div id="cubeviz-visualization-nothingFoundNotification">
                No data fits to your selection, please adapt your selection in the left sidebar manually.
                <br/>
                <br/>
                
                <div id="cubeviz-visualization-nothingFoundNotificationLink">
                    <img src="<?php echo $this->cubevizImagesPath; ?>arrow-down.png" class="cubeviz-icon-micro" id="cubeviz-Index-NothingFoundNotificationLink">
                    &nbsp;
                    <a>Why do i sometimes receive an empty chart / no data?</a>
                </div>
            </div>            
            <br/>            
            <div id="cubeviz-visualization-nothingFoundFurtherExplanation">
                <div style="float:left;">
                    <img class="cubeviz-icon-minimal"
                         src="<?php echo $this->cubevizImagesPath; ?>questionmark.png" 
                         style="opacity:0.3;"/>
                </div>
                <div style="margin-left: 24px; margin-top:-3px;">
                    <span style="font-size:16px; font-weight:bold;">
                        Explanation
                    </span>
                    <p>
                        This behavior can have various reasons. On the one hand it
                        is possible that there is no data available according to 
                        the selection. In order to reduce the load of the server 
                        we decided not to check the availability of data for every 
                        selection. 
                        <br/>
                        <br/>
                        On the other hand it is possible that a chart can not be 
                        produced if the user selects inapplicable combinations of 
                        options such as a logarithm scale in combination 
                        with percentage stacking. Trapping such cases is not yet 
                        fully implemented but will be done soon.
                        <br/>
                        <br/>
                        To solve such problems we suggest to change the selection 
                        and/or the selected chart options.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 
    Dialog box for questionmark in headline(cubeviz-Index-questionMarkHeadline) 
-->
<div id="cubeviz-index-headerDialogBox">
    
    <!-- Label -->
    <h2><?php echo $this->CubeViz_ModelInformation ['rdfs:label']; ?></h2>
    
    <!-- Short description -->
    <div style="font-size: 14px;"><?php echo $this->CubeViz_ModelInformation ['doap:shortdesc']; ?></div>
        
    <!-- Description -->
    <small><?php echo $this->CubeViz_ModelInformation ['dc:description']; ?></small>
    
    <br/>
    <br/>
    <div style="font-size: 14px;">Information:</div>
    
    <ul class="cubeviz-ul-basic">
        <!-- Creator -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>person-pencil.png" class="cubeviz-icon-minimal" title="Creator"/>
            <?php echo $this->CubeViz_ModelInformation ['dc:creator']; ?>
        </li>
    
        <!-- Revision -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>version2.png" class="cubeviz-icon-minimal" title="Revision"/>
            Revision: <?php echo $this->CubeViz_ModelInformation ['doap:revision']; ?>
        </li>
    
        <!-- Document -->
        <li>
            <img src="<?php echo $this->cubevizImagesPath; ?>document.png" class="cubeviz-icon-minimal" title="License"/>
            <?php echo $this->CubeViz_ModelInformation ['doap:license']; ?>
        </li>
    </ul>
</div>
