<h2><?php echo $this->_translate->_('Welcome to the CubeViz application. '); ?></h2>
<?php echo $this->_translate->_('With CubeViz you can visualize statistical data in different chart types.'); ?>
<br/>
<h2><?php echo $this->_translate->_('What I should do next? '); ?></h2>
<?php echo $this->_translate->_('You see this page, because you did not specify any configuration parameters. '); ?>
<?php echo $this->_translate->_('To get started, please specify a model for visualization. '); ?>
<?php echo $this->_translate->_('For instance, you can do it by appending ?m=graphURI (which is registered in the store) to link in your browser address bar. '); ?>
<?php echo $this->_translate->_('Change graphURI to the model you want to visualize.'); ?>
<br/>
<h2><?php echo $this->_translate->_('Or simply use following link to see how it works.'); ?></h2>
<br/>
<a href="<?php echo $this->cubevizPath; ?>?m=http://data.lod2.eu/scoreboard/&chartType=area">To start click here!</a>
