<div id="stringContainerChartSelector_Array" style="display:none;">
    {.section entries}
    
        {.repeated section @}
        
            <div class="chartMenuItem" style="clear:both;">
                <div style="float:left; font-size:13px; font-weight:bold;">{label}</div>
            
                <div style="float:right">
                    <select name="chartMenuItem_{key}" key="{key}" style="width: 100px; min-width: 100px; max-width: 100px; ">
                    {.repeated section values}
                    <option value="{@}">{@}</option>        
                    {.end}
                    </select>
                </div>
            </div>
            
        {.end}
          
    {.or}{.end}
</div>
    
<script type="text/javascript">

    var ChartSelector_Array = $("#stringContainerChartSelector_Array").html ();
    
</script>
