<div id="stringContainerDimensionsTemplate" style="display:none;">
    {.section dimensions}
        {.repeated section @}
            
            <div class="sidebar-left-data-selection-dims-box-label-value">
               <span style="float:left;">{label}</span> 
               <span style="float:left;" id="dialog-{label}-selected-items">&nbsp;({selectedElementCount} / {elementCount})</span>
                <span style="float:right;" id="open-dialog-{label}-selector" class="open-dialog-selector" dimensionLabel="{label}" dimensionUrl="{url}" dimensionType="{type}">
                    <img class="sidebar-left-data-selection-dims-box-abstract-img" src="<?php echo $this->moduleUrl; ?>static/images/check_book.png" title="<?php echo $this->_translate->_('Select some elements'); ?>">
                </span>
            </div>
                
        {.end}    
    {.or}{.end}
</div>


<div id="stringContainerDialogTemplate" style="display:none;">
    <div class="dialog" id="dialog-{dimensionLabel}">
        <div class="dialog-header">
            <div class="dialog-header-label">{dimensionLabel}</div>
            <div style="float:right;">
                <input type="button" id="dialog-btn-close-{dimensionLabel}" class="minibutton submit" dimensionLabel="{dimensionLabel}" dimensionType="{dimensionType}" dimensionUrl="{dimensionUrl}" value="<?php echo $this->_translate->_('Save'); ?>">
            </div>
        </div>
        <div class="dialog-components">
            <ul>
            {.repeated section list}
                <li>
                    <input type="checkbox" name="{dimensionUrl}" class="dialog-checkbox-{dimensionLabel}" value="{property}" propertyLabel="{property_label}" property="{property}"/>
                    <label class="dialog-listitem-value">{property_label}</label>
                </li>
            {.end}
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">

    var CubeViz_Dimension_Template = $("#stringContainerDimensionsTemplate").html ();
    var CubeViz_Dialog_Template = $("#stringContainerDialogTemplate").html ();
    
</script>
