<div id="stringContainerDimensionsTemplate" style="display:none;">
    {.section dimensions}
        {.repeated section @}
            
            <div class="sidebar-left-data-selection-dims-box-seperator" style="margin-left: 1px; margin-top: 10px;">
                <div class="sidebar-left-data-selection-dims-box-lblabs">
                    <div class="sidebar-left-data-selection-dims-box-label" style="float: left;">
                        <span class="sidebar-left-data-selection-dims-box-label-value">{label}</span> 
                        (<span id="dialog-{label}-selected-items">{selectedElementCount}/</span>{elementCount})
                    </div>
                    <div class="sidebar-left-data-selection-dims-box-abstract">
                        <div id="open-dialog-{label}-selector" class="open-dialog-selector" dimensionLabel="{label}" dimensionUrl="{url}" dimensionType="{type}">
                            <img class="sidebar-left-data-selection-dims-box-abstract-img" src="<?php echo $this->moduleUrl; ?>static/images/check_book.png" title="<?php echo $this->_translate->_('Select some elements'); ?>">
                        </div>
                        <div style="display:none;" id="open-dialog-{label}-options" class="open-dialog-options">
                            <img class="sidebar-left-data-selection-dims-box-abstract-img" src="<?php echo $this->moduleUrl; ?>static/images/settings.png" title="<?php echo $this->_translate->_('Options'); ?>">
                        </div>
                    </div>
                </div>
                <input style="display:none;" type="checkbox" class="sidebar-left-data-selection-dims-box" id="sidebar-left-data-selection-dims-box-{label}" name="" value="{url}">
            </div>     
                          
        {.end}    
    {.or}{.end}
</div>


<div id="stringContainerMeasuresTemplate" style="display:none;">
    {.section measures}	
        {.repeated section @}
            <div class="sidebar-left-data-selection-meas-box-seperator">
                <input style="display:none;" type="checkbox" name="" class="sidebar-left-data-selection-meas-box" id="sidebar-left-data-selection-meas-box-{label}" value="{url}"/>
                <div class="sidebar-left-data-selection-meas-box-label">&nbsp; {label}</div>
                <div class="sidebar-left-data-selection-meas-box-abstract">
                    <div style="display:none;" id="open-dialog-{label}-options">
                        <img class="sidebar-left-data-selection-meas-box-abstract-img" src="<?php echo $this->moduleUrl; ?>static/images/settings.png" title="<?php echo $this->_translate->_('Options'); ?>"/>
                    </div>
                </div>
            </div>
        {.end}    
    {.or}{.end}
</div>


<div id="stringContainerDialogTemplate" style="display:none;">
    <div class="dialog" id="dialog-{dimensionUrl}">
        <div class="dialog-header">
            <div class="dialog-header-label">{dimensionLabel}</div><div class="dialog-header-label-warning">Only 10 elements are selectable at the same time.</div>
            <div style="float:right;">
                <input type="button" id="dialog-btn-close-{dimensionLabel}" class="minibutton submit" dimensionLabel="{dimensionLabel}" dimensionType="{dimensionType}" dimensionUrl="{dimensionUrl}" value="<?php echo $this->_translate->_('Save'); ?>">
            </div>
        </div>
        <div class="dialog-components">
            <ul>
            {.repeated section list}
                <li>
                    <input type="checkbox" name="{dimensionUrl}" class="dialog-checkbox-{dimensionLabel}" value="{property}" propertyLabel="{property_label}" property="{property}"/>
                    <label class="dialog-listitem-value">{property_label}</label>
                </li>
            {.end}
            </ul>
        </div>
    </div>
</div>


<div id="stringContainerOptionsDimensionTemplate" style="display:none;">
    
    <div class="dialog-options-dimension" id="dialog-options-dimension-{label}">
        
        <div id="dialog-options-dimension-btn-close-{label}" class="dialog-options-dimension-btn-close"><?php echo $this->_translate->_('Save'); ?></div>
        
        <h2><?php echo $this->_translate->_('Dimension'); ?>: {label}</h2>
        <div class="dialog-options-dimension-items">
        
            <div class="dialog-options-dimension-items-floatblock">
                <b><?php echo $this->_translate->_('Order Direction'); ?></b>
                <span id="dialog-options-dimension-order-direction-value-{label}" style="display:none;">{orderDirection}</span>
                <br/>
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="None" 
                       class="dialog-options-dimension-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('None'); ?>
                <br/>
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="Ascending" 
                       class="dialog-options-dimension-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('Ascending'); ?>
                <br/>    
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="Descending" 
                       class="dialog-options-dimension-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('Descending'); ?>
            </div>
            
            <div class="dialog-options-dimension-items-floatblock">
                <b><?php echo $this->_translate->_('Chart Axis'); ?></b>
                <span id="dialog-options-dimension-chart-axis-value-{label}" style="display:none;">{chartAxis}</span>
                <br/>
                <input type="radio" 
                       name="chart-axis-{label}" 
                       value="x" 
                       class="dialog-options-dimension-items-chart-axis-{label}"/>x
                <br/>
                <!-- input type="radio" 
                       name="chart-axis" 
                       value="y" 
                       class="dialog-options-dimension-items-chart-axis-{label}"/>y
                <br/ -->    
                <input type="radio" 
                       name="chart-axis-{label}" 
                       value="z" 
                       class="dialog-options-dimension-items-chart-axis-{label}"/>y
                       <!-- the Z axis on the back end is actually Y axis in real life -->
            </div>

        </div>
    </div>
</div>


<div id="stringContainerOptionsMeasureTemplate" style="display:none;">
       
    <div class="dialog-options-measure" id="dialog-options-measure-{label}">
        <h2><?php echo $this->_translate->_('Measure'); ?>: {label}</h2>
        <div class="dialog-options-measure-items">
            <b><?php echo $this->_translate->_('Aggregation Method'); ?></b>
            <span id="dialog-options-measure-aggregation-method-value-{label}" style="display:none;">{aggregationMethod}</span>
            <br/>
                <input type="radio" 
                       name="aggregation-method-{label}" 
                       value="sum" 
                       class="dialog-options-measure-items-aggregation-method-{label}"/>
                <?php echo $this->_translate->_('sum'); ?>
            <br/>
                <input type="radio" 
                       name="aggregation-method-{label}" 
                       value="average" 
                       class="dialog-options-measure-items-aggregation-method-{label}"/>
                <?php echo $this->_translate->_('average'); ?>
            <br/>    
                <input type="radio" 
                       name="aggregation-method-{label}" 
                       value="minimum" 
                       class="dialog-options-measure-items-aggregation-method-{label}"/>
                <?php echo $this->_translate->_('minimum'); ?>
            <br/>
                <input type="radio" 
                       name="aggregation-method-{label}" 
                       value="maximum" 
                       class="dialog-options-measure-items-aggregation-method-{label}"/>
                <?php echo $this->_translate->_('maximum'); ?>
            <br/>
            <br/>
            
            <b><?php echo $this->_translate->_('Order Direction'); ?></b>
            <span id="dialog-options-measure-order-direction-value-{label}" style="display:none;">{orderDirection}</span>
            <br/>
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="None" 
                       class="dialog-options-measure-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('None'); ?>
            <br/>
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="Ascending" 
                       class="dialog-options-measure-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('Ascending'); ?>
            <br/>    
                <input type="radio" 
                       name="order-direction-{label}" 
                       value="Descending" 
                       class="dialog-options-measure-items-order-direction-{label}"/>
                <?php echo $this->_translate->_('Descending'); ?>
            <br/>
            <br/>
            
            <b><?php echo $this->_translate->_('Round Value?'); ?></b>
            <span id="dialog-options-measure-round-values-value-{label}" style="display:none;">{roundValues}</span>
            <br/>
                <input type="radio" 
                       name="round-values-{label}" 
                       value="yes" 
                       class="dialog-options-measure-items-round-values-{label}"/>
                <?php echo $this->_translate->_('Yes'); ?>
            <br/>
                <input type="radio" 
                       name="round-values-{label}" 
                       value="no" 
                       class="dialog-options-measure-items-round-values-{label}"/>
                <?php echo $this->_translate->_('No'); ?>
            <br/>

        </div>
    
        <div id="dialog-options-measure-btn-close-{label}" class="dialog-options-measure-btn-close"><?php echo $this->_translate->_('Save'); ?></div>
    </div>
    
</div>
    
<script type="text/javascript">

    var CubeViz_Dimension_Template = $("#stringContainerDimensionsTemplate").html ();
    var CubeViz_Measure_Template = $("#stringContainerMeasuresTemplate").html ();
    var CubeViz_Dialog_Template = $("#stringContainerDialogTemplate").html ();
    var CubeViz_Options_Dimension_Template = $("#stringContainerOptionsDimensionTemplate").html ();
    var CubeViz_Options_Measure_Template = $("#stringContainerOptionsMeasureTemplate").html ();
    
</script>
