<div id="stringContainerDimensionsTemplate" style="display:none;">
    {.section dimensions}
        {.repeated section @}
            
            <div class="sidebar-left-data-selection-dims-box-label-value">
               <span style="float:left;">{label}</span> 
               <span style="float:left;" id="dialog-{label}-selected-items">&nbsp;({selectedElementCount} / {elementCount})</span>
                <span style="float:right;" id="open-dialog-{hashedUrl}-selector" class="open-dialog-selector" label="{label}" hashedUrl="{hashedUrl}" typeUrl="{typeUrl}" url="{url}">
                    <img class="sidebar-left-data-selection-dims-box-abstract-img" src="<?php echo $this->moduleUrl; ?>public/images/check_book.png" title="<?php echo $this->_translate->_('Select some elements'); ?>">
                </span>
            </div>
                
        {.end}    
    {.or}{.end}
</div>


<div id="stringContainerDialogTemplate" style="display:none;">
    <div class="dialog" id="dialog-{label}">
        <div class="dialog-header">
            <div class="dialog-header-label">{label}</div>
            <div style="float:right;">
                <input type="button" id="dialog-btn-close-{hashedUrl}" class="minibutton submit" hashedUrl="{hashedUrl}" label="{label}" typeUrl="{typeUrl}" url="{url}" value="<?php echo $this->_translate->_('Update and close'); ?>">
            </div>
        </div>
        <div class="dialog-components">
            <ul>
            {.repeated section list}
                <li>
                    <input type="checkbox" name="{url}" class="dialog-checkbox-{hashedUrl}" value="{property}" propertyLabel="{propertyLabel}" property="{property}"/>
                    <label class="dialog-listitem-value">{propertyLabel}</label>
                </li>
            {.end}
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">

    var CubeViz_Dimension_Template = $("#stringContainerDimensionsTemplate").html ();
    var CubeViz_Dialog_Template = $("#stringContainerDialogTemplate").html ();
    
</script>
